// File generated by FlutterFire CLI.
// ---------------------------------------------------------
// IMPORTANT: This is a PLACEHOLDER file.
//
// Do NOT use this file as-is. Instead, replace this entire
// file by running the following command in your project root:
//
//   flutterfire configure
//
// This command will:
//   1. Ask you to select (or create) a Firebase project.
//   2. Ask which platforms to support (Android/iOS/Web).
//   3. Auto-generate a real version of this file with your
//      actual Firebase project's API keys and IDs.
//
// Prerequisites (run once):
//   dart pub global activate flutterfire_cli
//   npm install -g firebase-tools
//   firebase login
//
// See README.md for the full step-by-step setup guide.
// ---------------------------------------------------------

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run `flutterfire configure` to generate this file properly.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Android - '
          'run `flutterfire configure` to generate this file properly.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'run `flutterfire configure` to generate this file properly.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform - '
          'run `flutterfire configure` to generate this file properly.',
        );
    }
  }
}
